name: Publish OpenTofu Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create package archive
      run: |
        mkdir -p dist
        tar -czf dist/opentofu-multi-cloud-infrastructure.tar.gz \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='dist' \
          --exclude='*.tfstate*' \
          --exclude='.terraform' \
          .
    
    - name: Upload package to GitHub Packages
      uses: actions/upload-artifact@v4
      with:
        name: opentofu-multi-cloud-infrastructure
        path: dist/opentofu-multi-cloud-infrastructure.tar.gz
        retention-days: 30 